### ISSUE TITLE
Dělení a slučování textových atomů

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/folio#100]
Prosím o návrh nástroje, který on hover umožní (za uzavřeným odstavcem textu, titulkem, seznamem atp.) rozdělit textový atom na dva, aby bylo možné snadněji vložit doprostřed jiný. Pravděpodobně v jednom kroku jako ikona přidání. Podobně by bylo dobré mít možnost za sebou řazené textové atomy sloučit do jednoho.

**Comment by hoxgen** [comment]
Přikládám návrhy. Pls @mreq koukni, zda je to za tebe proveditelné:

Rozdělení
<img width="1993" alt="rozdeleni" src="https://user-images.githubusercontent.com/1716158/153377307-2de3cf86-c7c4-4f11-bcfb-b9fb85e5f54f.png">

Sloučení
<img width="1582" alt="slouceni" src="https://user-images.githubusercontent.com/1716158/153377321-cd5030c1-f93f-4534-b0c9-755fb4cf152e.png">

@ornsteinfilip

**Comment by hoxgen** [comment]
@mreq dík, upravil jsem to obecně bez specifikace počtu 

@ornsteinfilip posílám náhledy, link do [Figmy ](https://www.figma.com/file/nsF3MJkKTvw7xujDtyA48v/Folio---Console?node-id=1481%3A4083) bych jim nedával, protože tam jsou i další části console pro různé jiné klienty.

<img width="2019" alt="Snímek obrazovky 2022-02-10 v 14 32 52" src="https://user-images.githubusercontent.com/1716158/153418682-c33f9a28-02cf-4b0d-8ea7-679262501d42.png">
<img width="1597" alt="Snímek obrazovky 2022-02-10 v 14 33 01" src="https://user-images.githubusercontent.com/1716158/153418696-addca12a-5929-47b4-9994-ea022bf5bc08.png">

**Comment by ornsteinfilip** [comment]
Váže se na implementaci Football clubu
