### ISSUE TITLE
Atom v molekule zmizí, pokud se přidá další atom nad molekulu.

### ISSUE THREAD

**Issue by VladaTrefil** [sinfin/folio#166]
Postup pro replikaci na prázdné stránce.

1. přidá se 2x atom s molekulou
2. Nad ně se přidá jakýkoliv atom
3. zmizí jeden atom z molekuly

- Pokud je stránka uložena po přidání molekuly, tak atom v molekule zmizí jenom v náhledu a po obnovení stránky se znovu objeví. 
- Pokud je atom i molekula přidaná najednou, tak po uložení jeden atom z molekuly zmizí úplně.

Zkoušel jsem to na acb a icecz.

**Comment by hoxgen** [comment]
@VeronikaCizkova tohle pls nějak prioritizovat, je to docela nepříjemná věc na více projektech zároveň

**Comment by mreq** [comment]
3367de51e0573da25c619001f1c3bc829062949c
