### ISSUE TITLE
Blocks updates

### ISSUE THREAD

**Issue by davidduben** [sinfin/folio#236]
Title, 1 column (text previously), divider, quotation, logos, documents

- [x] **Title:**

https://www.figma.com/file/lR9K0yYlfS0zic4ygo8aF6/Folio---Design-System?type=design&node-id=4433%3A15766&mode=design&t=skhfdHmAaIqnb19e-1

- [x] **1 column:**

https://www.figma.com/file/lR9K0yYlfS0zic4ygo8aF6/Folio---Design-System?type=design&node-id=4605%3A14373&mode=design&t=skhfdHmAaIqnb19e-1

- [x] **Quotation:**

https://www.figma.com/file/lR9K0yYlfS0zic4ygo8aF6/Folio---Design-System?type=design&node-id=5141%3A58947&mode=design&t=skhfdHmAaIqnb19e-1

- [x] **Documents**

https://www.figma.com/design/lR9K0yYlfS0zic4ygo8aF6/Folio---Design-System?node-id=5175%3A16442&t=hUgwxr6l5ypvUDWO-1

- [x] **Divider**

https://www.figma.com/design/lR9K0yYlfS0zic4ygo8aF6/Folio---Design-System?node-id=5186%3A15514&t=hUgwxr6l5ypvUDWO-1

**Comment by ornsteinfilip** [comment]
@densimn Prosím o kontrolu WIP blocků

**Comment by densimn** [comment]
Zkontroloval a pridal jsem zbyvajici Figma odkazy.

**Comment by VladaTrefil** [comment]
Hotovo, v masteru.
