### ISSUE TITLE
Console: lepší výběr a editace atomů

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/folio#254]
- [ ] výběr atomů
- [ ] live náhledy (existuje, dělal @mreq)
- [ ] editace atomů

Design: https://www.figma.com/design/nOwyEu7mbQ25ZHxdj6JurJ/Folio---Console-Design?node-id=73%3A3870&t=j7Jxy9LmtF09DViH-1

**Comment by ornsteinfilip** [comment]
@hoxgen @densimn @mreq Pro naplánování této issue by bylo dobré ještě probrat možnost vzniku explicitní molekuly, tedy wrapperu pro případy jako více sloupcový obsah, blokový hisghlight více atomů atp.

**Comment by mreq** [comment]
Tohle neni aktualni @ornsteinfilip @VeronikaCizkova , udelame cele jinak s Economia. Nema tedy ani smysl dnesni meet?

**Comment by VeronikaCizkova** [comment]
@mreq můžeme teda uzavřít, že nebudeme dělat? Meet zruším. cc: @VladaTrefil

**Comment by mreq** [comment]
ano
