### ISSUE TITLE
Non-space white char in keyword is breaks tag input

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/folio#3]
Example:
```
 [#<ActsAsTaggableOn::Tag:0x007fdd9a20ef48 id: 392, name: "grease", taggings_count: 1>,
 #<ActsAsTaggableOn::Tag:0x007fdd9a20ed18 id: 393, name: "starvation", taggings_count: 1>,
 #<ActsAsTaggableOn::Tag:0x007fdd9a20ebb0 id: 394, name: "EHD&#160;lubrication", taggings_count: 1>]
```
... but in the form si visible only one tag
<img width="796" alt="screenshot 2019-01-25 16 47 17" src="https://user-images.githubusercontent.com/595642/51756284-ea67ed80-20c0-11e9-824b-e4eae07da8f4.png">

**Comment by dedekm** [comment]
this is not because of white space char
the rest of tags get deleted, because they aren't available in `options` (because they doesn't fit in the `.limit(1000)`)

remove the limit and it will work (and use `.pluck(:name)` not `.map(&:name)` :wink: )
