### ISSUE TITLE
Change mail delivery from Sendgrid SMTP to API

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/folio#40]
We are emailing to inform you of an upcoming requirement to update your authentication method with Twilio SendGrid to API keys exclusively by December 9th, 2020 in order to ensure uninterrupted service and improve the security of your account. Our records show that one or more users with this email address used basic authentication with username and password for one or more of your SendGrid API requests in the last 30 days. If you do not take action, those API requests will be rejected on December 9th, 2020.

Why API keys?
This is an effort to enhance security for all of our users. Using your account username and password for authentication is less secure than using an API Key. Unlike your username and password, API Keys are uniquely generated and can be set to limit the access and specify permissions for a given request. 

What action is required? 
Follow these steps to identify and replace your authentication method to API Keys and then implement Two-Factor Authentication (2FA) for enhanced security.

What happens if no action is taken?
On December 9th, 2020 we will no longer accept basic authentication with username and password, and we will be requiring 2FA to login to your account. If you attempt to authenticate your API requests or SMTP configuration with username and password for any of your users after that date, your requests will be rejected.

We’d like to thank you in advance for your prompt attention to these requirements. If you’d like to learn more about how you can enhance the security of your account, view this post. If you have any questions or need assistance, please visit our documentation or our Support team.

Thank you,
The Twilio SendGrid Team

https://sendgrid.com/docs/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys/
https://sendgrid.com/blog/7-best-practices-to-protect-your-twilo-sendgrid-account-and-sending-reputation/

**Comment by ornsteinfilip** [comment]
We've to change delivery method for Folio CMS and migrate all running projects before 9th December.

**Comment by dedekm** [comment]
https://github.com/eddiezane/sendgrid-actionmailer (uses twilio managed gem https://github.com/sendgrid/sendgrid-ruby)

**Comment by ornsteinfilip** [comment]
We are emailing to inform you of the new deadline date of January 20th, 2021 to update your authentication method with Twilio SendGrid to API keys exclusively in order to ensure uninterrupted service and improve the security of your account. Our records show that one or more users with this email address used basic authentication with username and password for one or more of your SendGrid API requests or SMTP integration in the last 30 days. If you do not take action, **those API requests will be rejected on January 20th, 2021.**
