### ISSUE TITLE
Ošetřit vícenásobné generování náhledů ve Foliu

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/folio#41]
Na několika projektech máme akutní problém se zahlcováním fronty generování náhledů z obrázků. V principu se stane, že se při každém uživatelském requestu na stránku obsahující náhled obrázku volá nový job `Folio::GenerateThumbnailJob` a tyto jsou umístěny fe frontě souběžně a často i souběžně běží. Na některých webech/url jde i o vyšší tisíce jobů. Tím dochází k ucpání fronty (produkční nastavební sidekiqu čítá např jen 10-30 paralelních jobů).

Stejně tak je problém s novým jobem `Folio::SetFileAdditionalDataJob`.

**Možnosti, jak řešit problém...**
- při vkládání do fronty zkontrolovat, jestli v ní již není job se stejným parametrem (id obrázku a crop string)
- před rozběhnutím jobu zkontrolovat, zda již není vygenerováno (pokud není force), tj. URL pro dané rozlišení je již uložena
- před rozběhnutím zkontrolovat existenci PID file, který obsahuje jak id obrázku, tak crop string (nestačí při paralelních worker serverech)
- pro více nezávislých workerů před rozběhnutím zkontrolovat příznak PID a čas spuštění uložený v db/redis u obrázku, ale počítat s možností, že job spadl a tyto informace nesmazal
- počítat s možmostí, že job spadl a PID file nebo db příznak po sobě nesmazal i přes to, že toto musí být v ensure nehledě na typ výjimky ... tzn kontrolovat čas zámku a čase větším, než X sekund zamknout pro sebe a udělat
- job by mohl v paralelním vláknu sledovat, zda nejsou splněny podmínky viz výše a umět se ukončit (běžící joby totiž nejde ze Sidekiqu vyřazovat, musí být ve frontě, nebo toto implementovat samy)

**Comment by mreq** [comment]
Imho by stacilo pridat hned v thumb metode placeholder hash s datumem. Kdyz tam bude a datum minus ted bude treba do 15 minut, tak se nepusti novy job, ale bude se cekat.

**Comment by dedekm** [comment]
> před rozběhnutím jobu zkontrolovat, zda již není vygenerováno (pokud není force), tj. URL pro dané rozlišení je již uložena  

to tam mame https://github.com/sinfin/folio/blob/master/app/jobs/folio/generate_thumbnail_job.rb#L13
a asi to tedy nestaci, je potreba aby se ty joby vubec do fronty neradily

ten zpusob co popisuje @mreq by asi stacit, akorat bude kazdy `thumb` delat update modelu

**Comment by ornsteinfilip** [comment]
Po přechodu na K8s to je ještě palčivější problém.

<img width="1198" alt="Snímek obrazovky 2021-04-06 v 11 22 12" src="https://user-images.githubusercontent.com/595642/113689266-6c54f780-96ca-11eb-82d0-43b45c617f57.png">

**Comment by ornsteinfilip** [comment]
@foton Zkus prosím kouknout na řešení č. 2 a 3
https://blog.francium.tech/avoiding-duplicate-jobs-in-sidekiq-dcbb1aca1e20

**Comment by mreq** [comment]
7d93e1c2
