### ISSUE TITLE
`shell` pro Dragonfly vyhazuje vyjímku u nenainstalovaného `jpegtran`

### ISSUE THREAD

**Issue by foton** [sinfin/folio#48]
Pokud není nainstalovaný `jpegtran`, pak
volání [`if shell("which", "jpegtran").blank?`](https://github.com/sinfin/folio/blob/master/config/initializers/dragonfly.rb#L50)  skončí s `RuntimeError: Failed: 'which jpegtran' failed with ''. Stdout: ''.`
Neboť: ` Open3.capture3("which", "jpegtran") => => ["", "", #<Process::Status: pid 103105 exit 1>]`  [viz](https://github.com/sinfin/folio/blob/b235bcec27834b0112cb9c2dbc19bc54935976e8/config/initializers/dragonfly.rb#L16)

**Comment by foton** [comment]
Podobně to pak u `Folio::Image` vystřelí kvůli chybějícímu `cwebp`
```
ragonfly::Shell::CommandFailed: Command failed: cwebp /tmp/dragonfly20210207-110216-f2xahr.jpg -o /tmp/dragonfly20210207-110216-jaa2mw.webp, , error: No such file or directory - cwebp
```

**Comment by ornsteinfilip** [comment]
Upgradem na libvips se resi
