### ISSUE TITLE
CStypo / Jednoznakové předložky > pevná mezera 

### ISSUE THREAD

**Issue by hoxgen** [sinfin/folio#51]
V minulosti jsme pro správnou typografii používali https://github.com/sinfin/cstypo 

Chtěl bych z toho udělat folio default a promítnout tu funkci i do MM Spektra

Můžem víc prodiskutovat tady

**Comment by mreq** [comment]
Ve foliu uz je, staci jen pridat na MM https://github.com/sinfin/folio/blob/48027f0d1e6fb8891ada30810875a79d2129ec95/app/helpers/folio/cstypo_helper.rb

**Comment by hoxgen** [comment]
@mreq super, dal bych to defaultně zapnuté
