### ISSUE TITLE
Mizející `create_folio_unaccent` při `db:migrate:redo`

### ISSUE THREAD

**Issue by foton** [sinfin/folio#56]
@mreq  se to prý děje taky

Při použití `db:migrate:redo` se ze `schema.rb` smaže řádek `create_folio_unaccent` .
Vypadá to, že když se udělá totéž dvoukrokově `db:rollback` a `db:migrate` tak se to neděje.

**Comment by mreq** [comment]
Kdyz se ale rollback a migrate pusti v jednom radku (asi stejne jako redo), tak to take zmizi

```
rake db:rollback db:migrate
```

**Comment by dedekm** [comment]
zvlastni melo by se to vkladat vzdy po `db:schema:dump`
https://github.com/sinfin/folio/blob/master/lib/tasks/folio/pg.rake

priznavam ze `db:migrate:redo` jsem ani neznal, podivam se na to
