### ISSUE TITLE
Update na Dragonfly 1.4 - convert processor is deprecated

### ISSUE THREAD

**Issue by dedekm** [sinfin/folio#66]
update dragonfly z 1.3 na 1.4 rozbije generovani nahledu  

`The convert processor is deprecated for better security - use Dragonfly::ImageMagick::Commands.convert(content, args, opts) instead.`

viz.
https://github.com/markevans/dragonfly/blob/35e88d14987bf425dcace67f9b100d9a23cae904/History.md#140-2021-05-19

**Comment by ornsteinfilip** [comment]
Budeme řešit pomocí Libvips, viz #42
