### ISSUE TITLE
Atom text s obrázkem - doplnit lightbox pro obrázek

### ISSUE THREAD

**Issue by hoxgen** [sinfin/folio#74]
<img width="1685" alt="Snímek obrazovky 2021-07-22 v 12 07 05" src="https://user-images.githubusercontent.com/1716158/126623222-1644be51-8076-47ce-be7a-f283e2364c3a.png">

Obrázek by mělo být možné zvětšit do lightboxu. Týká se i Aukce Aukcí.

**Comment by mreq** [comment]
9f6ee6d0
