### ISSUE TITLE
Console / editor: zvýraznění tlačítka "hotovo" v úpravě atomu

### ISSUE THREAD

**Issue by hoxgen** [sinfin/folio#89]
- [x] Zvýraznění tlačítka "hotovo" > [figma](https://www.figma.com/file/nsF3MJkKTvw7xujDtyA48v/Folio---Console?node-id=1481%3A4083)

**Comment by hoxgen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Folio UX zlepšení náměty](https://trello.com/c/SME2ejxt/52-folio-ux-zlep%C5%A1en%C3%AD-n%C3%A1m%C4%9Bty)

**Comment by VladaTrefil** [comment]
@mreq Zkoušel jsem změnit třídu toho tlačítka, ale neprojevuje se to, koukni na to a pak mi prosím trochu popiš jak tohle funguje. commit: 56a9177fc52be76ae89bd571bb1e3c6f1d5784ad

**Comment by mreq** [comment]
@VladaTrefil To si upravil nejaky jiny soubor. Je potreba upravit `react/src/components/AtomForm/index.js` a buildnout react. Udelam
