### ISSUE TITLE
Console / editor - fixed ovládací prvky redaktor.js textového pole

### ISSUE THREAD

**Issue by hoxgen** [sinfin/folio#92]
Pokud je text dlohý a mám nascrollováno dolu, je obtížné např. vytučnit něco, co je dole pod foldem. Lepčí proto prosím přichytit ovládací prvky do okna inputu fixně, aby byly vidět stále:

<img width="930" alt="Snímek obrazovky 2021-12-21 v 10 57 58" src="https://user-images.githubusercontent.com/1716158/146910379-f7544d1e-1780-491c-b67d-6094fb0b3818.png">

**Comment by hoxgen** [comment]
cc @mreq

**Comment by hoxgen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Folio UX zlepšení náměty](https://trello.com/c/SME2ejxt/52-folio-ux-zlep%C5%A1en%C3%AD-n%C3%A1m%C4%9Bty)

**Comment by ornsteinfilip** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plovoucí menu u textu](https://trello.com/c/fRgrS8MY/76-plovouc%C3%AD-menu-u-textu)

**Comment by VladaTrefil** [comment]
Tohle bohuzel nativne nefunguje, ten toolbarFixed: true uz tam je a nic to nedela, kupodivu jeste narozdil od example v dokumentaci jezdi toolbar v show source modu. Udelal jsem na to workaround.

V issue je tomu nejbliz asi tohle, ale to je tak 5 let stary. https://github.com/craftcms/redactor/issues/9

Je mozny ze za to muze tohle, my mame 3.1.7 na gazetistu, kde jsem to zkousel.
https://imperavi.com/redactor/log/
![2023-08-22 20-04](https://github.com/sinfin/folio/assets/34059901/d0143e58-bfb9-4cbc-afc0-a73d9a4fef46)

Udelal jsem css workaround, ktery bez problemu funguje. Ale samozrejme bylo by lepsi to vyresit nativne.

```
.redactor-toolbar-wrapper
  position: sticky
  background: white
  top: -1px
  z-index: 10000

  .redactor-toolbar
    background: inherit

```

@mreq Jak bys postupoval dal? Myslis ze ma smysl hledat funkcni verzi, nebo tam dame ten css workaround?

**Comment by mreq** [comment]
jestli to pravdu funguje, tak nevidim v css override problem

**Comment by VladaTrefil** [comment]
@VeronikaCizkova @hoxgen Hotovo. Nahrano na infocz, NPM, Gazetisto

Squared je pozadu 70 commitu, Gazetisto zase 40 commitu. Bude potreba update. Klidne bych to udelal po domluve s @mreq.

**Comment by mreq** [comment]
Squared by ted mel byt na vicemene aktualni v4. U gazetista (ktere je na v4) problem s upgradem nepredpokladam. Klidne se pust do obou.

**Comment by VladaTrefil** [comment]
Tohle bude lepsi udelat pri folio update, zaviram.
